import type { Metadata } from "next";
import { Montserrat } from "next/font/google";  // Import Montserrat from next/font/google
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });  // Use Montserrat font

export const metadata: Metadata = {
  title: "Sandeep Kumar Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
